// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArk0xvlXre7_-SKMHSRBdAUNnLQ21tUo4',
    appId: '1:306042006359:web:3f056ff75e596fc09a6c12',
    messagingSenderId: '306042006359',
    projectId: 'team-management-ibzh11',
    authDomain: 'team-management-ibzh11.firebaseapp.com',
    storageBucket: 'team-management-ibzh11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz70lZDz3tbHRZ4k2m_2GqdeoMV6lqOKA',
    appId: '1:306042006359:android:e9dd6f29a47b0e199a6c12',
    messagingSenderId: '306042006359',
    projectId: 'team-management-ibzh11',
    storageBucket: 'team-management-ibzh11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc0-2mxT9_AIuURWlA9POv6YggpSpeBp8',
    appId: '1:306042006359:ios:129bf51ff19af3ba9a6c12',
    messagingSenderId: '306042006359',
    projectId: 'team-management-ibzh11',
    storageBucket: 'team-management-ibzh11.appspot.com',
    iosClientId: '306042006359-87kp1td94b74fberjpef8b1j8f06ijqa.apps.googleusercontent.com',
    iosBundleId: 'com.ibzh11.app',
  );
}
